@ECHO OFF
REM BFCPEOPTIONSTART
REM Advanced BAT to EXE Converter www.BatToExeConverter.com
REM BFCPEEXE=C:\Users\natal\Desktop\GUI\BARBrowser.exe
REM BFCPEICON=C:\Users\natal\Desktop\GUI\guiicon.ico
REM BFCPEICONINDEX=-1
REM BFCPEEMBEDDISPLAY=0
REM BFCPEEMBEDDELETE=1
REM BFCPEADMINEXE=0
REM BFCPEINVISEXE=1
REM BFCPEVERINCLUDE=1
REM BFCPEVERVERSION=1.0.0.0
REM BFCPEVERPRODUCT=BARBrowser
REM BFCPEVERDESC=BARBrowser (not compatiple)
REM BFCPEVERCOMPANY=BARBrowser TM
REM BFCPEVERCOPYRIGHT=(C) 2024
REM BFCPEWINDOWCENTER=1
REM BFCPEDISABLEQE=0
REM BFCPEWINDOWHEIGHT=30
REM BFCPEWINDOWWIDTH=120
REM BFCPEWTITLE=no care
REM BFCPEOPTIONEND
@echo off
REM Execute the PowerShell command
powershell -Command ".\gui.ps1"